## 介绍
NumPy是 Python 科学计算的核心库，提供 ndarray（N 维数组对象），支持：  
向量化运算（无需循环，整批计算）  
多维数据结构（图片 = 3 维数组、数据集 = 2 维数组）  
底层 C 语言优化，高性能数值计算  
所有机器学习 / 视觉库（Pandas、Matplotlib、PyTorch、OpenCV）的底层依赖  

In [2]:
# 导入NumPy库,np 输入常见缩写
import numpy as np

### 核心对象——————ndarray数组
`ndarray` = `N-dimensional array`,**连续内存存储的同类型数据合集**，是所有数值计算的基础单元

#### 1. 从列表创建：np.array()

In [3]:
# 一维数组（特征数据）
arr1 = np.array([1,2,3,4,5])
print(arr1,"\n")
# 二维数组（表格/灰度图）
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2,"\n")
# 三维数组（彩色图片：高 x 宽 x 通道）
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)

[1 2 3 4 5] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### 全0数组：`np.zeros()`

In [4]:
# 模拟纯黑图片（480，640，3）
img_black = np.zeros((480,640,3),dtype = np.uint8)